services:
  - postgresql
addons:
  postgresql: '12'
language: node_js
node_js:
  - 'stable'
install: npm install
cashe:
  directories:
    - node_modules
script:
  - npm run dev
  - npm run test

after_success: npm run coverage
